-- A view merging rcap_pfh_adult_child and rcap_pfh_parent

create or replace view view_pfh_adult_child_parent_union
as
select
    creation_time,
    last_updated_ts,
    source_subject_id,
    language,
    record_dag_name,
    -- hc18_administrator as administrator,
    -- hc18_administrator_other as administrator_other,
    hc18_parent1_relationship as parent1_relationship,
    hc18_parent1_relat_other as parent1_relat_other,
    hc18_parent_year as parent_year,
    hc18_bio_mother_race as bio_mother_race,
    hc18_bio_mother_race_other as bio_mother_race_other,
    hc18_bio_mother_ethnicity as bio_mother_ethnicity,
    hc18_bio_father_race as bio_father_race,
    hc18_bio_father_race_other as bio_father_race_other,
    hc18_bio_father_ethnicity as bio_father_ethnicity,
    hc18_parent_yob as parent_yob,
    hc18_parent1_sex as parent1_sex,
    hc18_parent1_race as parent1_race,
    hc18_parent1_race_mult as parent1_race_mult,
    hc18_parent1_hispanic as parent1_hispanic,
    hc18_parent1_birth_country as parent1_birth_country,
    hc18_parent1_country_other as parent1_country_other,
    hc18_parent1_child_relig as parent1_child_relig,
    hc18_parent1_c_relig_other as parent1_c_relig_other,
    hc18_parent1_relig_now as parent1_relig_now,
    hc18_par1_relig_now_other as par1_relig_now_other,
    hc18_parent1_relig_import as parent1_relig_import,
    hc18_parent1_educ as parent1_educ,
    hc18_parent_relat as parent_relat,
    hc18_parent2_yod as parent2_yod,
    hc18_parent_sep as parent_sep,
    hc18_parent_visit as parent_visit,
    hc18_parent_relat_status as parent_relat_status,
    hc18_parent2_relat_status as parent2_relat_status,
    hc18_parent2_yob as parent2_yob,
    hc18_parent2_gender as parent2_gender,
    hc18_parent2_race as parent2_race,
    hc18_parent2_race_other as parent2_race_other,
    hc18_parent2_hispanic as parent2_hispanic,
    hc18_parent2_birth_country as parent2_birth_country,
    hc18_parent2_country_other as parent2_country_other,
    hc18_parent2_c_relig as parent2_c_relig,
    hc18_parent2_c_relig_other as parent2_c_relig_other,
    hc18_parent2_relig_now as parent2_relig_now,
    hc18_par2_relig_now_other as par2_relig_now_other,
    hc18_parent2_relig_import as parent2_relig_import,
    hc18_parent2_educ as parent2_educ,
    hc18_residence as residence,
    hc18_residence_other as residence_other,
    hc18_residence_child as residence_child,
    hc18_residence_parent1 as residence_parent1,
    hc18_residence_partner as residence_partner,
    hc18_residence_gparents as residence_gparents,
    hc18_residence_siblings as residence_siblings,
    hc18_residence_other_adults as residence_other_adults,
    hc18_residence_other_children as residence_other_children,
    hc18_residence_unrelat_adults as residence_unrelat_adults,
    hc18_residence_unrelat_children as residence_unrelat_children,
    hc18_residence_sum_v2 as residence_sum_v2,
    hc18_non_residence_siblings as non_residence_siblings,
    hc18_sib1_age as sib1_age,
    hc18_sib2_age as sib2_age,
    hc18_sib3_age as sib3_age,
    hc18_sib4_age as sib4_age,
    hc18_sib5_age as sib5_age,
    hc18_sib6_age as sib6_age,
    hc18_sib7_age as sib7_age,
    hc18_sib8_age as sib8_age,
    hc18_sib9_age as sib9_age,
    hc18_sib10_age as sib10_age,
    hc18_sib11_age as sib11_age,
    hc18_sib12_age as sib12_age,
    hc18_pet as pet,
    hc18_pet_type__1_dog as pet_type__1_dog,
    hc18_pet_other as pet_other,
    hc18_house_income as house_income,
    hc18_dep__0_child as dep__0_child,
    hc18_ad__0_child as ad__0_child,
    hc18_bipolar__0_child as bipolar__0_child,
    hc18_ptsd__0_child as ptsd__0_child,
    hc18_schiz__0_child as schiz__0_child,
    hc18_autism__0_child as autism__0_child,
    hc18_add__0_child as add__0_child,
    hc18_alc_abuse__0_child as alc_abuse__0_child,
    hc18_thc_abuse__0_child as thc_abuse__0_child,
    hc18_drug_abuse__0_child as drug_abuse__0_child,
    hc18_exp_to_trauma__0_child as exp_to_trauma__0_child,
    hc18_suicide_att__0_child as suicide_att__0_child,
    hc18_suicide_death__0_child as suicide_death__0_child,
    hc18_complete as complete,
    project_id,
    event_name,
    survey_identifier,
    hc18_pet_type__2_cat as pet_type__2_cat,
    hc18_pet_type__3_rodent as pet_type__3_rodent,
    hc18_pet_type__4_reptile as pet_type__4_reptile,
    hc18_pet_type__5_fish as pet_type__5_fish,
    hc18_pet_type__6_other as pet_type__6_other,
    hc18_dep__1_you as dep__1_you,
    hc18_ad__1_you as ad__1_you,
    hc18_bipolar__1_you as bipolar__1_you,
    hc18_ptsd__1_you as ptsd__1_you,
    hc18_schiz__1_you as schiz__1_you,
    hc18_autism__1_you as autism__1_you,
    hc18_add__1_you as add__1_you,
    hc18_alc_abuse__1_you as alc_abuse__1_you,
    hc18_thc_abuse__1_you as thc_abuse__1_you,
    hc18_drug_abuse__1_you as drug_abuse__1_you,
    hc18_exp_to_trauma__1_you as exp_to_trauma__1_you,
    hc18_suicide_att__1_you as suicide_att__1_you,
    hc18_suicide_death__1_you as suicide_death__1_you,
    hc18_dep__2_othpar as dep__2_othpar,
    hc18_ad__2_othpar as ad__2_othpar,
    hc18_bipolar__2_othpar as bipolar__2_othpar,
    hc18_ptsd__2_othpar as ptsd__2_othpar,
    hc18_schiz__2_othpar as schiz__2_othpar,
    hc18_autism__2_othpar as autism__2_othpar,
    hc18_add__2_othpar as add__2_othpar,
    hc18_alc_abuse__2_othpar as alc_abuse__2_othpar,
    hc18_thc_abuse__2_othpar as thc_abuse__2_othpar,
    hc18_drug_abuse__2_othpar as drug_abuse__2_othpar,
    hc18_exp_to_trauma__2_othpar as exp_to_trauma__2_othpar,
    hc18_suicide_att__2_othpar as suicide_att__2_othpar,
    hc18_suicide_death__2_othpar as suicide_death__2_othpar,
    hc18_dep__3_brother as dep__3_brother,
    hc18_ad__3_brother as ad__3_brother,
    hc18_bipolar__3_brother as bipolar__3_brother,
    hc18_ptsd__3_brother as ptsd__3_brother,
    hc18_schiz__3_brother as schiz__3_brother,
    hc18_autism__3_brother as autism__3_brother,
    hc18_add__3_brother as add__3_brother,
    hc18_alc_abuse__3_brother as alc_abuse__3_brother,
    hc18_thc_abuse__3_brother as thc_abuse__3_brother,
    hc18_drug_abuse__3_brother as drug_abuse__3_brother,
    hc18_exp_to_trauma__3_brother as exp_to_trauma__3_brother,
    hc18_suicide_att__3_brother as suicide_att__3_brother,
    hc18_suicide_death__3_brother as suicide_death__3_brother,
    hc18_dep__4_sister as dep__4_sister,
    hc18_ad__4_sister as ad__4_sister,
    hc18_bipolar__4_sister as bipolar__4_sister,
    hc18_ptsd__4_sister as ptsd__4_sister,
    hc18_schiz__4_sister as schiz__4_sister,
    hc18_autism__4_sister as autism__4_sister,
    hc18_add__4_sister as add__4_sister,
    hc18_alc_abuse__4_sister as alc_abuse__4_sister,
    hc18_thc_abuse__4_sister as thc_abuse__4_sister,
    hc18_drug_abuse__4_sister as drug_abuse__4_sister,
    hc18_exp_to_trauma__4_sister as exp_to_trauma__4_sister,
    hc18_suicide_att__4_sister as suicide_att__4_sister,
    hc18_suicide_death__4_sister as suicide_death__4_sister,
    'pfh_adult_child' as instrument
from rcap_pfh_adult_child

union all

select
    creation_time,
    last_updated_ts,
    source_subject_id,
    language,
    record_dag_name,
    -- hp_administrator as administrator,
    -- hp_administrator_other as administrator_other,
    hp_parent1_relationship as parent1_relationship,
    hp_parent1_relat_other as parent1_relat_other,
    hp_parent_year as parent_year,
    hp_bio_mother_race as bio_mother_race,
    hp_bio_mother_race_other as bio_mother_race_other,
    hp_bio_mother_ethnicity as bio_mother_ethnicity,
    hp_bio_father_race as bio_father_race,
    hp_bio_father_race_other as bio_father_race_other,
    hp_bio_father_ethnicity as bio_father_ethnicity,
    hp_parent_yob as parent_yob,
    hp_parent1_sex as parent1_sex,
    hp_parent1_race as parent1_race,
    hp_parent1_race_mult as parent1_race_mult,
    hp_parent1_hispanic as parent1_hispanic,
    hp_parent1_birth_country as parent1_birth_country,
    hp_parent1_country_other as parent1_country_other,
    hp_parent1_child_relig as parent1_child_relig,
    hp_parent1_c_relig_other as parent1_c_relig_other,
    hp_parent1_relig_now as parent1_relig_now,
    hp_par1_relig_now_other as par1_relig_now_other,
    hp_parent1_relig_import as parent1_relig_import,
    hp_parent1_educ as parent1_educ,
    hp_parent_relat as parent_relat,
    hp_parent2_yod as parent2_yod,
    hp_parent_sep as parent_sep,
    hp_parent_visit as parent_visit,
    hp_parent_relat_status as parent_relat_status,
    hp_parent2_relat_status as parent2_relat_status,
    hp_parent2_yob as parent2_yob,
    hp_parent2_gender as parent2_gender,
    hp_parent2_race as parent2_race,
    hp_parent2_race_other as parent2_race_other,
    hp_parent2_hispanic as parent2_hispanic,
    hp_parent2_birth_country as parent2_birth_country,
    hp_parent2_country_other as parent2_country_other,
    hp_parent2_c_relig as parent2_c_relig,
    hp_parent2_c_relig_other as parent2_c_relig_other,
    hp_parent2_relig_now as parent2_relig_now,
    hp_par2_relig_now_other as par2_relig_now_other,
    hp_parent2_relig_import as parent2_relig_import,
    hp_parent2_educ as parent2_educ,
    hp_residence as residence,
    hp_residence_other as residence_other,
    hp_residence_child as residence_child,
    hp_residence_parent1 as residence_parent1,
    hp_residence_partner as residence_partner,
    hp_residence_gparents as residence_gparents,
    hp_residence_siblings as residence_siblings,
    hp_residence_other_adults as residence_other_adults,
    hp_residence_other_children as residence_other_children,
    hp_residence_unrelat_adults as residence_unrelat_adults,
    hp_residence_unrelat_children as residence_unrelat_children,
    hp_residence_sum_v2 as residence_sum_v2,
    hp_non_residence_siblings as non_residence_siblings,
    hp_sib1_age as sib1_age,
    hp_sib2_age as sib2_age,
    hp_sib3_age as sib3_age,
    hp_sib4_age as sib4_age,
    hp_sib5_age as sib5_age,
    hp_sib6_age as sib6_age,
    hp_sib7_age as sib7_age,
    hp_sib8_age as sib8_age,
    hp_sib9_age as sib9_age,
    hp_sib10_age as sib10_age,
    hp_sib11_age as sib11_age,
    hp_sib12_age as sib12_age,
    hp_pet as pet,
    hp_pet_type__1_dog as pet_type__1_dog,
    hp_pet_other as pet_other,
    hp_house_income as house_income,
    hp_dep__0_child as dep__0_child,
    hp_ad__0_child as ad__0_child,
    hp_bipolar__0_child as bipolar__0_child,
    hp_ptsd__0_child as ptsd__0_child,
    hp_schiz__0_child as schiz__0_child,
    hp_autism__0_child as autism__0_child,
    hp_add__0_child as add__0_child,
    hp_alc_abuse__0_child as alc_abuse__0_child,
    hp_thc_abuse__0_child as thc_abuse__0_child,
    hp_drug_abuse__0_child as drug_abuse__0_child,
    hp_exp_to_trauma__0_child as exp_to_trauma__0_child,
    hp_suicide_att__0_child as suicide_att__0_child,
    hp_suicide_death__0_child as suicide_death__0_child,
    hp_complete as complete,
    project_id,
    event_name,
    survey_identifier,
    hp_pet_type__2_cat as pet_type__2_cat,
    hp_pet_type__3_rodent as pet_type__3_rodent,
    hp_pet_type__4_reptile as pet_type__4_reptile,
    hp_pet_type__5_fish as pet_type__5_fish,
    hp_pet_type__6_other as pet_type__6_other,
    hp_dep__1_you as dep__1_you,
    hp_ad__1_you as ad__1_you,
    hp_bipolar__1_you as bipolar__1_you,
    hp_ptsd__1_you as ptsd__1_you,
    hp_schiz__1_you as schiz__1_you,
    hp_autism__1_you as autism__1_you,
    hp_add__1_you as add__1_you,
    hp_alc_abuse__1_you as alc_abuse__1_you,
    hp_thc_abuse__1_you as thc_abuse__1_you,
    hp_drug_abuse__1_you as drug_abuse__1_you,
    hp_exp_to_trauma__1_you as exp_to_trauma__1_you,
    hp_suicide_att__1_you as suicide_att__1_you,
    hp_suicide_death__1_you as suicide_death__1_you,
    hp_dep__2_othpar as dep__2_othpar,
    hp_ad__2_othpar as ad__2_othpar,
    hp_bipolar__2_othpar as bipolar__2_othpar,
    hp_ptsd__2_othpar as ptsd__2_othpar,
    hp_schiz__2_othpar as schiz__2_othpar,
    hp_autism__2_othpar as autism__2_othpar,
    hp_add__2_othpar as add__2_othpar,
    hp_alc_abuse__2_othpar as alc_abuse__2_othpar,
    hp_thc_abuse__2_othpar as thc_abuse__2_othpar,
    hp_drug_abuse__2_othpar as drug_abuse__2_othpar,
    hp_exp_to_trauma__2_othpar as exp_to_trauma__2_othpar,
    hp_suicide_att__2_othpar as suicide_att__2_othpar,
    hp_suicide_death__2_othpar as suicide_death__2_othpar,
    hp_dep__3_brother as dep__3_brother,
    hp_ad__3_brother as ad__3_brother,
    hp_bipolar__3_brother as bipolar__3_brother,
    hp_ptsd__3_brother as ptsd__3_brother,
    hp_schiz__3_brother as schiz__3_brother,
    hp_autism__3_brother as autism__3_brother,
    hp_add__3_brother as add__3_brother,
    hp_alc_abuse__3_brother as alc_abuse__3_brother,
    hp_thc_abuse__3_brother as thc_abuse__3_brother,
    hp_drug_abuse__3_brother as drug_abuse__3_brother,
    hp_exp_to_trauma__3_brother as exp_to_trauma__3_brother,
    hp_suicide_att__3_brother as suicide_att__3_brother,
    hp_suicide_death__3_brother as suicide_death__3_brother,
    hp_dep__4_sister as dep__4_sister,
    hp_ad__4_sister as ad__4_sister,
    hp_bipolar__4_sister as bipolar__4_sister,
    hp_ptsd__4_sister as ptsd__4_sister,
    hp_schiz__4_sister as schiz__4_sister,
    hp_autism__4_sister as autism__4_sister,
    hp_add__4_sister as add__4_sister,
    hp_alc_abuse__4_sister as alc_abuse__4_sister,
    hp_thc_abuse__4_sister as thc_abuse__4_sister,
    hp_drug_abuse__4_sister as drug_abuse__4_sister,
    hp_exp_to_trauma__4_sister as exp_to_trauma__4_sister,
    hp_suicide_att__4_sister as suicide_att__4_sister,
    hp_suicide_death__4_sister as suicide_death__4_sister,
    'pfh_parent' as instrument
from rcap_pfh_parent;


