--- lab_view_ctau_v5
---
--- Construct a view to generate output from the DW for the individual labs using Dr. Champagne’s Lab as a filter: 
---     (si.si_tube_id ilike '%_1_1') 
--- Include the following base demographics, dates, and curation source variables to associate CTAU instrument records to tube_ids.
---			DOB
---			Date of blood collection
---			Calculated age (in days) at date of blood collection; age_in_days should only be provided to the labs;  
---            use age_in_months or years for all other deidentified data products.
---			tube_id
---			sex
---         base demograpics (race and ethnicity)
---
--- Separate views for CTAU vs CTRN psychosocial data to provide clarity for separate data collection dates, ie. separate "baseline" dates for CTAU vs CTRN.
--- 
--- Data from the REDCap CTAU project includes: 
---         tlfb alcohol/tobacco/thc consumption
---         audit 
---         sui
---         deq 
---
--- Data from the separate REDCap CTRN Main project file includes:
---			personal family histories
---			tesic (# traumas, worst traumas, and most recent traumas by category)
---			tesip (age at first trauma exposure)
---			mini (primary diagnosis)
---         ctx (child assistance for individual and family therapy, psych hospital admission and psych prescriptions)  
---			audit AUDIT score
---         capsca (ptsd data) 
---         phqa
---         scared child
---         chrt16
---         casss child and casss adult (18+ years old)
---
--- Duplicates, pii/phi, and fields not specifically required by the labs are generated by the view but removed before sharing.
--- Date-based calculations in days should only be shared with the are limited to access
---
--- Other notes: 
---         Specimens sent to Drs Champagne (Epigenomics tube_ids ending in 1_1), Ressler (Genetics tube_ids ending in 2_1),
---         and Beurel (Cytokines tube_ids ending in 3_1). 
---         Genetics lab only requires baseline data.
---         Epigenomics and cytokine labs require data from all (follow-up) sample collections.
---
---  
select
  subject_id
	,source_subject_id as ctau_source_subject_id -- PII CTAU record_id; Remove after curation
  ,sched_ctrn_id		-- PII CTRN Main record_id; Remove after curation
  ,si_tube_id
	,event_name
	,case
	  when event_name like 'baseline%' then to_char(sched_base_complete_date,'mm/dd/yyyy')
	  when event_name like 'six_month%' then to_char(sched_6mo_complete_date,'mm/dd/yyyy')
	  when event_name like 'one_year%' then to_char(sched_1yr_date,'mm/dd/yyyy')
	  when event_name like '24_month%' then to_char(sched_2yr_complete_date,'mm/dd/yyyy')
	end as sched_ctau_complete_date -- PII. Remove after curation.                             -- PII. CTAU visit completion date; remove after curation
  ,si_freeze_dt_tm     -- PII. Best date to use for sample collection; remove before sharing 
  ,dem_ch_dob  -- PII; Remove after curation
  ,case 
    when event_name like 'baseline%' then age_days_between(dem_ch_dob::date, sched_base_complete_date)
    when event_name like 'six_month%' then age_days_between(dem_ch_dob::date, sched_6mo_complete_date)
    when event_name like 'one_year%' then age_days_between(dem_ch_dob::date, sched_1yr_date)
    when event_name like '24_month%' then age_days_between(dem_ch_dob::date, sched_2yr_complete_date)
  end as age_days_interview
  ,age_days_between(dem_ch_dob::date, si_freeze_dt_tm::date) as age_days_sample_collection
  ,case
    when event_name like 'baseline%' then sched_base_complete
    when event_name like 'six_month%' then sched_6mo_complete
    when event_name like 'one_year%' then sched_1yr_complete
    when event_name like '24_month%' then sched_2yr_complete
  end as complete
  ,case
    when event_name like 'baseline%' then '00_baseline'
    when event_name like 'six_month%' then '06_six_month'
    when event_name like 'one_year%' then '12_month'
    when event_name like '24_month%' then '24_month'
    end as visit
  ,sex
  ,hc_race as race
  ,hc_hispanic as hispanic
  ,tlfb_drink_mo
  ,tlfb_drink_days
  ,tlfb_drink_per_day
  ,tlfb_hv_ep_dr_days
  ,tlfb_24_max
  ,tlfb_cig_mo
  ,tlfb_smoke_days
  ,tlfb_cig_per_day
  ,tlfb_thc_days
  ,audit_q1_sc
	,audit_q2_sc
	,audit_q3_sc
	,audit_q4_sc
  ,audit_q5_sc
  ,audit_q6_sc
  ,audit_q7_sc
  ,audit_q8_sc
  ,audit_q9_sc
	,audit_q10_sc
  ,audit_score 
  ,sui_1
  ,sui_2
	,sui_3
	,sui_4 
	,sui_5
--- ,sui_6		         Unstructured text needs to be deidentified or removed prior to public sharing
 	,sui_7
	,sui_8
  ,age_years_between(deq_alc_use_dt::date, dem_ch_dob::date) as deq_age_last_alc -- NEW FIELD
  ,age_days_between(deq_alc_use_dt::date, si_freeze_dt_tm::date) AS deq_last_alc_days_b4sample	   
	,deq_alc_last_amt
	,deq_alc_dur
  ,deq_alc_mem_diff
  ,deq_alc_blackout
	,deq_alc_hungover
  ,deq_alc_effects
	,deq_alc_effects_2
	,deq_alc_effects_3
  ,deq_alc_effects_4
  ,age_years_between(deq_drug_use_dt::date, dem_ch_dob::date) as deq_age_last_drug
	,age_days_between(deq_drug_use_dt::date, si_freeze_dt_tm::date) AS deq_last_drug_days_b4sample
  ,deq_drug_mdma
  ,deq_drug_heroin
  ,deq_drug_cocaine 
	,deq_drug_crack
  ,deq_drug_k
	,deq_drug_meth
	,deq_drug_pain
  ,deq_drug_stim
  ,deq_drug_k2
 	,deq_drug_benzos 
  ,deq_drug_none
  ,deq_drugs_dur
  ,deq_drugs_snort
 	,deq_drugs_inject
	,deq_drugs_smoke
	,deq_drugs_oral
	,deq_drugs_other
	,deq_drugs_mem_diff
  ,deq_drugs_blackout
	,deq_drugs_hungover
  ,deq_drugs_effects
	,deq_drugs_effects_2
	,deq_drugs_effects_3	
from rcap_ctau_sample_info_joined_view si
where si_tube_id ilike '%_1_1';






------- 05/13/26 Vlad commented out Pat's part of the script 

-- inner join subject_alias sa1
--     on sa1.source_subject_id = si.source_subject_id
--     and sa1.project_id = 2515 -- only ctau ids
--     and sa1.id_type = 'redcap'
-- left join rcap_ctau_scheduling_form sched
--     on sched.source_subject_id = si.source_subject_id 
--     and sched.event_name like 'baseline%'             -- Is this right? Need all events in which samples were collected.
-- left join rcap_ctau_dem ctau_dem
--     on ctau_dem.source_subject_id = sa1.source_subject_id
-- left join rcap_ctau_tlfb tlfb
--     on tlfb.source_subject_id = sa1.source_subject_id
-- left join rcap_ctau_audit aud
--     on aud.source_subject_id = sa1.source_subject_id
-- left join rcap_ctau_sui sui
--     on sui.source_subject_id = sa1.source_subject_id
-- left join rcap_ctau_deq deq
--     on deq.source_subject_id = sa1.source_subject_id
-- left join subject_alias sa3
--     on sa3.subject_id = sa1.subject_id
--     and sa3.project_id = 696
--     and sa3.id_type = 'redcap'
-- left join rcap_pfh_child pfhc 
--     on pfhc.source_subject_id = sa3.source_subject_id
-- 	and pfhc.event_name like 'baseline%'               -- Is this right? Need all events in which samples were collected.
-- order by sa1.subject_id; 
