--- lab_view_ctrn_v5.sql
---
--- Construct a view to generate output from the DW for the individual labs using Dr. Champagne’s Lab as a filter: 
---     (si.si_tube_id ilike '%_1_1') 
--- Include the following base demographics, dates, and curation source variables to associate CTAU instrument records to tube_ids.
---			DOB
---			Date of blood collection
---			Calculated age (in days) at date of blood collection; age_in_days should only be provided to the labs;  
---            use age_in_months or years for all other deidentified data products.
---			tube_id
---			sex
---         base demograpics (race and ethnicity)
---
--- Separate views for CTAU vs CTRN psychosocial data to provide clarity for separate data collection dates, ie. separate "baseline" dates for CTAU vs CTRN.
--- 
--- Data from the REDCap CTAU project includes: 
---         tlfb alcohol/tobacco/thc consumption
---         audit 
---         sui
---         deq 
---
--- Data from the separate REDCap CTRN Main project file includes:
---			personal family histories
---			tesic (# traumas, worst traumas, and most recent traumas by category)
---			tesip (age at first trauma exposure)
---			mini (primary diagnosis)
---         ctx (child assistance for individual and family therapy, psych hospital admission and psych prescriptions)  
---			audit AUDIT score
---         capsca (ptsd data) 
---         phqa
---         scared child
---         chrt16
---         casss child and casss adult (18+ years old)
---
--- Duplicates, pii/phi, and fields not specifically required by the labs are generated by the view but removed before sharing.
--- Date-based calculations in days should only be shared with the are limited to access
---
--- Other notes: 
---         Specimens sent to Drs Champagne (Epigenomics tube_ids ending in 1_1), Ressler (Genetics tube_ids ending in 2_1),
---         and Beurel (Cytokines tube_ids ending in 3_1). 
---         Genetics lab only requires baseline data.
---         Epigenomics and cytokine labs require data from all (follow-up) sample collections.
---
---  
select si_tube_id,
	   subject_id,
	   source_subject_id,   -- PII CTAU record_id; Remove after curation
---    Rename events to following "visit" names: 00_baseline, 01_one_month, 06_six_month, 12_month, 24_month	
       event_name,
       sched_ctrn_id,		-- PII CTRN Main record_id; Remove after curation
---    project_id,			-- REDCap PID; remove after curation
---    id_type,             -- Identifies REDCap or other source; remove after curation
       si_freeze_dt_tm,     -- PII. Best date to use for sample collection; remove before sharing 
       sched_ctau_complete_date,  -- PII. Curation reference: the CTAU schedule visit complete date _dt; remove after curation
       sched_ctrn_complete_date,  -- PII. Curation reference: the MAIN schedule visit complete date _dt; remove after curation
	   tc_interview_date,   -- PII. Best date for calculating tesic completion? Remove after curation  
       dem_ch_dob,  -- PII; Remove after curation
---    case 
---          when event_name like 'baseline%' then age_days_between(dem_ch_dob::date, sched_base_complete_date)
---          when event_name like 'one_year%' then age_days_between(dem_ch_dob::date, sched_1yr_date)
---          when event_name like '24_month%' then age_days_between(dem_ch_dob::date, sched_2yr_complete_date)
---    end as age_days,
       age_days_between(dem_ch_dob::date, si_freeze_dt_tm) as age_days_sample_collection,
       case
             when event_name like 'baseline%' then sched_base_complete
             when event_name like 'one_year%' then sched_1yr_complete
             when event_name like '24_month%' then sched_2yr_complete
       end as complete,
       sex,
	   hc_race as race,
  	   hc_hispanic as hispanic,
       pfha_u.instrument,
       pfha_u.parent1_relationship,
       pfha_u.parent1_sex,
       pfha_u.parent1_educ,
       pfha_u.parent2_gender,
       pfha_u.parent2_educ,
	   pfha_u.alc_abuse__0_child,
       pfha_u.alc_abuse__1_you,
       pfha_u.alc_abuse__2_othpar,
       pfha_u.alc_abuse__3_brother,
       pfha_u.alc_abuse__4_sister,
       pfha_u.thc_abuse__0_child,
       pfha_u.thc_abuse__1_you,
       pfha_u.thc_abuse__2_othpar,
       pfha_u.thc_abuse__3_brother,
       pfha_u.thc_abuse__4_sister,
       pfha_u.drug_abuse__0_child,
       pfha_u.drug_abuse__1_you,
       pfha_u.drug_abuse__2_othpar,
       pfha_u.drug_abuse__3_brother,
       pfha_u.drug_abuse__4_sister,
---
--- tesic, tcfu, tesip and associated calculations	
---
       coalesce (tc_1_1, tcfu_1_1) as tc_1_1,
       tc_1_1_crit_a1,
	   tc_1_1_how_often,
       tp_1_1_age_first,
       tc_1_1_worst, -- Worst checkboxes from baseline and tcfu; the coalesced variable name should be entered as tc_8_1.
       coalesce (tc_1_2, tcfu_1_2) as tc_1_2,
       tc_1_2_crit_a1,
       tc_1_2_how_often,
       tp_1_2_age_first,
       tc_1_2_worst,
       coalesce (tc_1_3, tcfu_1_3) as tc_1_3,
       tc_1_3_crit_a1,
       tc_1_3_how_often,
       tp_1_3_age_first,
       tc_1_3_worst,
       coalesce (tc_1_4, tcfu_1_4) as tc_1_4,
  	   tc_1_4_crit_a1,
       tc_1_4_how_often,
       tp_1_4a_age_first,
       tp_1_4b_age_first,
       tc_1_4_worst,
       coalesce (tc_1_5, tcfu_1_5) as tc_1_5,
       tc_1_5_crit_a1,
       tc_1_5_how_often,
       tp_1_5_age_first,
       tc_1_5_worst,
       coalesce (tc_1_6, tcfu_1_6) as tc_1_6,
  	   tc_1_6_crit_a1,
       tc_1_6_how_often,
       tp_1_6_age_first,
       tc_1_6_worst,
       coalesce (tc_2_1, tcfu_2_1) as tc_2_1,
       tc_2_1_crit_a1,
       tc_2_1_how_often,
       tp_2_1_age_first,
       tc_2_1_worst,
       coalesce (tc_2_2, tcfu_2_2) as tc_2_2,
	   tc_2_2_crit_a1,
       tc_2_2_how_often,
       tp_2_2_age_first,
       tc_2_2_worst,
       coalesce (tc_2_3, tcfu_2_3) as tc_2_3,
	   tc_2_3_crit_a1,
       tc_2_3_how_often,
       tp_2_3_age_first,
       tc_2_3_worst,
       coalesce (tc_2_4, tcfu_2_4) as tc_2_4,
       tc_2_4_crit_a1,
       tc_2_4_how_often,
       tp_2_4_age_first,
       tc_2_4_worst,
       coalesce (tc_2_5, tcfu_2_5) as tc_2_5,
  	   tc_2_5_crit_a1,
       tc_2_5_how_often,
       tp_2_5_age_first,
       tc_2_5_worst,
       coalesce (tc_3_1, tcfu_3_1) as tc_3_1,
	   tc_3_1_crit_a1,
       tc_3_1_how_often,
       tp_3_1_age_first,
       tc_3_1_worst,
       coalesce (tc_3_2, tcfu_3_2) as tc_3_2,
  	   tc_3_2_crit_a1,
       tc_3_2_how_often,
       tp_3_2_age_first,
       tc_3_2_worst,
       coalesce (tc_3_3, tcfu_3_3) as tc_3_3,
  	   tc_3_3_crit_a1,
       tc_3_3_how_often,
       tp_3_3_age_first,
       tc_3_3_worst,
       coalesce (tc_4_1, tcfu_4_1) as tc_4_1,
  	   tc_4_1_crit_a1,
       tc_4_1_how_often,
       tp_4_1_age_first,
       tc_4_1_worst,
       coalesce (tc_4_2, tcfu_4_2) as tc_4_2,
  	   tc_4_2_crit_a1,
       tc_4_2_how_often,
       tp_4_2_age_first,
       tc_4_2_worst,
       coalesce (tc_4_3, tcfu_4_3) as tc_4_3,
	     tc_4_3_crit_a1,
       tc_4_3_how_often,
       tp_4_3_age_first,
       tc_4_3_worst,
       coalesce (tc_5, tcfu_5) as tc_5,
  	   tc_5_crit_a1,
       tc_5_how_often,
       tp_5_1_age_first,
       tp_5_2_age_first,
       tc_5_worst,
       coalesce (tc_6_1, tcfu_6_1) as tc_6_1,
       tp_6_1_age_first,
       coalesce (tc_6_2, tcfu_6_2) as tc_6_2,
       tc_6_2_how_often,
       tp_6_2_age_first,
       coalesce (tc_7, tcfu_7) as tc_7,
  	   tc_7_crit_a1,
       tc_7_how_often,
       tp_7_1_age_first,
       tc_7_worst,
       tc_8_1 AS tc_worst,    -- Classification of the worst trauma within the period prior to the visit
       tc_8_1_less_than_1mo as tc_worst_less_than_1mo,
	   tc_8_2,                -- PII, date for calculating worst age and duration; remove after curation 
       age_years_between(tc_8_2::date, dem_ch_dob::date) AS worst_age_yrs,
       age_days_between(tc_8_2::date, tc_interview_date::date) AS worst_days_b4visit,
  	   age_days_between(tc_8_2::date, si_freeze_dt_tmdate) AS worst_days_b4sample,
	   tcfu_8_3 as tc_8_worst_ever,
	   tc_8_4,         -- PII, date of the most recent trauma reported at baseline; used to calculate age and recency; remove after curation
       tc_8_3 AS most_recent,   -- Classification of the most recent trauma
       tc_8_3_less_than_1mo as tc_most_recent_less_than_1mo, -- "1" indicates that the most recent trauma was less than 1 month prior to this visit 
       age_years_between(tc_8_4::date, dem_ch_dob::date) AS most_recent_trauma_age_yrs, -- Remove dates before sharing publicly
       age_days_between(tc_8_4::date, tc_interview_date::date) AS recent_days_b4visit,
	   age_days_between(tc_8_4::date, si_freeze_dt_tmdate) AS recent_days_b4sample,
	   --- tcfu_8_1 as tc_8_worst_last_6mo,          -- Are separate fields necessary? If not, combine with tc.
       --- tcfu_8_2 as tc_8_worst_last_6mo_date,     -- PII;  -- Are separate dates necessary? If not, combine with tc.
	   --- Criteria A1 trauma count subtotals and cumulative trauma variety index (unique trauma counts) TBD
	   tc_unintentional_a1_cnt,	     -- tc_1_1 thru tc_1_6 and tc_2_5 criteria a1   
	   tc_interpers_direct_a1_cnt,     -- tc_2_1 thru tc_2_4 and tc_5 criteria a1
 	   tc_interpers_witn_home_a1_cnt,  -- tc_3_1 thru tc_3_3 criteria a1
 	   tc_interpers_witn_comm_a1_cnt,  -- tc_4_1 thru tc_4_3 criteria a1
	   tc_bullying_cnt,                -- tc_6_1 and tc_6_2
       --- TBD: Nazan's cumulative trauma variety index (unique trauma counts) TBD
	   --- tc_cumvaridx_unintentional,	      -- unique cumulative count of tc_1_1 thru tc_1_6 and tc_2_5 criteria a1   
	   --- tc_cumvaridx_interpers_direct,     -- unique cumulative count of tc_2_1 thru tc_2_4 and tc_5 criteria a1
 	   --- tc_cumvaridx_interpers_witn_home,  -- unique cumulative count of tc_3_1 thru tc_3_3 criteria a1
 	   --- tc_cumvaridx_interpers_witn_comm,  -- unique cumulative count of tc_4_1 thru tc_4_3 criteria a1
	   --- tc_cumvaridx_bullying,             -- unique cumulative count of tc_6_1 and tc_6_2
---	   (
---            tc_cumvaridx_unintentional
---            + tc_cumvaridx_interpers_direct 
---            + tc_cumvaridx_interpers_witn_home 
---            + tc_cumvaridx_interpers_witn_comm 
---            + coalesce(tc_7_crit_a1::int,0)
---	   ) as tc_cumvaridx_life_overall,
---
--- Fields from rcap_child_assistance and mini
---
	   ctx.ctx_itx,         -- Child individual therapy treatment
	   ctx.ctx_iftx,        -- Family therapy treatment
       ctx.ctx_ipsy_hosp,   -- Child admitted to psych hospital
	   ctx.ctx_ipsy_meds,   -- Child prescribed psych meds
       mini.mini_primary_dx,
 
--- Fields from capsca (main)
       ,caps.caps_summary_a1
	   ,caps.caps_summary_b1_sev_q1
       ,caps.caps_summary_b2_sev_q2
       ,caps.caps_summary_b3_sev_q3
	   ,caps.caps_summary_b4_sev_q4
	   ,caps.caps_summary_b5_sev_q5
	   ,caps.caps_summary_c1_sev_q6
	   ,caps.caps_summary_c2_sev_q7
	   ,caps.caps_summary_d1_sev_q8
	   ,caps.caps_summary_d2_sev_q9
	   ,caps.caps_summary_d3_sev_q10
	   ,caps.caps_summary_d4_sev_q11
	   ,caps.caps_summary_d5_sev_q12
	   ,caps.caps_summary_d6_sev_q13
	   ,caps.caps_summary_d7_sev_q14
	   ,caps.caps_summary_e1_sev_q15	
	   ,caps.caps_summary_e2_sev_q16
	   ,caps.caps_summary_e3_sev_q17
	   ,caps.caps_summary_e4_sev_q18		
	   ,caps.caps_summary_e5_sev_q19	
	   ,caps.caps_summary_e6_sev_q20	
	   ,caps.caps_summary_f1_q22
	   ,caps.caps_summary_g1_sev_q23
	   ,caps.caps_summary_g2_sev_q24
	   ,caps.caps_summary_g3_sev_q25
	   ,caps.caps_summary_validity_q26
	   ,caps.caps_summary_severity_q27
	   ,caps.caps_summary_improve_q28
	   ,caps.caps_sum_depers_sev_q29
	   ,caps.caps_sum_dereal_sev_q30		
	   ,caps.caps_sum_ptsd_present		
	   ,caps.caps_summary_dissoc	
	   ,caps.caps_sum_delayed
	--- Additional data: phq-a
	   ,phqa.phq_1_val 
       ,phqa.phq_2_val
	   ,phqa.phq_3_val
	   ,phqa.phq_4_val
	   ,phqa.phq_5_val
	   ,phqa.phq_6_val
	   ,phqa.phq_7_val	
	   ,phqa.phq_8_val
	   ,phqa.phq_9_val
	   ,phqa.phqa_10
	   ,phqa.phqa_11
	   ,phqa.phqa_12
	   ,phqa.phqa_13
	---   
	--- Additional data: scared-child
	---
	   ,scaredc.scaredc_1
	   ,scaredc.scaredc_2
	   ,scaredc.scaredc_3
	   ,scaredc.scaredc_4
	   ,scaredc.scaredc_5
	   ,scaredc.scaredc_6
	   ,scaredc.scaredc_7
	   ,scaredc.scaredc_8
	   ,scaredc.scaredc_9
	   ,scaredc.scaredc_10
	   ,scaredc.scaredc_11
	   ,scaredc.scaredc_12
	   ,scaredc.scaredc_13
	   ,scaredc.scaredc_14
	   ,scaredc.scaredc_15
	   ,scaredc.scaredc_16
	   ,scaredc.scaredc_17
	   ,scaredc.scaredc_18
	   ,scaredc.scaredc_19
	   ,scaredc.scaredc_20
	   ,scaredc.scaredc_21
	   ,scaredc.scaredc_22
	   ,scaredc.scaredc_23
	   ,scaredc.scaredc_24
	   ,scaredc.scaredc_25
	   ,scaredc.scaredc_26
	   ,scaredc.scaredc_27
	   ,scaredc.scaredc_28
	   ,scaredc.scaredc_29
	   ,scaredc.scaredc_30
	   ,scaredc.scaredc_31
	   ,scaredc.scaredc_32
	   ,scaredc.scaredc_33
	   ,scaredc.scaredc_34
	   ,scaredc.scaredc_35
	   ,scaredc.scaredc_36
	   ,scaredc.scaredc_37
	   ,scaredc.scaredc_38
	   ,scaredc.scaredc_39
	   ,scaredc.scaredc_40
	   ,scaredc.scaredc_41
    ---   
	--- Additional data:  chrt16
	---	 
       ,chrt16.chrt_1
       ,chrt16.chrt_2
       ,chrt16.chrt_3
       ,chrt16.chrt_4
       ,chrt16.chrt_5
       ,chrt16.chrt_6
       ,chrt16.chrt_7
       ,chrt16.chrt_8
       ,chrt16.chrt_9
       ,chrt16.chrt_10
       ,chrt16.chrt_11
       ,chrt16.chrt_12
       ,chrt16.chrt_13
       ,chrt16.chrt_14
       ,chrt16.chrt_15
       ,chrt16.chrt_16
    ---   
	--- Additional data:  casss child
	---	
       ,casch.casch_sec1_q1a  -- My parent(s) show they are proud of me. - How often 1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q1b  -- My parent(s) show they are proud of me. - Important 1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q2a  -- My parent(s) understand me. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q2b  -- My parent(s) understand me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q3a  -- My parent(s) listen to me when I need to talk. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q3b  -- My parent(s) listen to me when I need to talk. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q4a  -- My parent(s) make suggestions when I don't know what to do. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q4b  -- My parent(s) make suggestions when I don't know what to do. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q5a  -- My parent(s) give me good advice. How often?	1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q5b  -- My parent(s) give me good advice. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q6a  -- My parent(s) help me solve problems by giving me information. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q6b  -- My parent(s) help me solve problems by giving me information. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q7a  -- My parent(s) tell me I did a good job when I do something well. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q7b  -- My parent(s) tell me I did a good job when I do something well. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q8a  -- My parent(s) nicely tell me when I make mistakes. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q8b  -- My parent(s) nicely tell me when I make mistakes. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q9a  -- My parent(s) reward me when I've done something well. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q9b  -- My parent(s) reward me when I've done something well. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q10a -- My parent(s) help me practice my activities. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q10b	-- My parent(s) help me practice my activities. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q11a	-- My parent(s) take time to help me decide things. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q11b	-- My parent(s) take time to help me decide things. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec1_q12a	-- My parent(s) get me many of the things I need. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec1_q12b	-- My parent(s) get me many of the things I need. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q1a	-- My teacher(s) cares about me. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q1b	-- My teacher(s) cares about me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q2a	-- My teacher(s) treats me fairly - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q2b	-- My teacher(s) treats me fairly - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q3a	-- My teacher(s) makes it okay to ask questions. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q3b	-- My teacher(s) makes it okay to ask questions. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q4a	-- My teacher(s) explains things that I don't understand. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q4b	-- My teacher(s) explains things that I don't understand. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q5a	-- My teacher(s) shows me how to do things. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q5b	-- My teacher(s) shows me how to do things. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q6a    -- My teacher(s) helps me solve problems by giving me information. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q6b	-- My teacher(s) helps me solve problems by giving me information. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q7a	-- My teacher(s) tells me I did a good job when I've done something well. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q7b	-- My teacher(s) tells me I did a good job when I've done something well. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q8a	-- My teacher(s) nicely tells me when I make mistakes. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q8b	-- My teacher(s) nicely tells me when I make mistakes. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q9a	-- My teacher(s) tells me how well I do on tasks. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q9b	-- My teacher(s) tells me how well I do on tasks. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q10a	-- My teacher(s) makes sure I have what I need for school. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q10b	-- My teacher(s) makes sure I have what I need for school. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q11a   -- My teacher(s) takes time to help me learn to do something well. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q11b	-- My teacher(s) takes time to help me learn to do something well. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec2_q12a	-- My teacher(s) spends time with me when I need help. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec2_q12b	-- My teacher(s) spends time with me when I need help. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q1a	-- My classmate(s) treat me nicely. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q1b	-- My classmate(s) treat me nicely. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q2a	-- My classmate(s) like most of my ideas and opinions. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q2b	-- My classmate(s) like most of my ideas and opinions. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q3a	-- My classmate(s) pay attention to me. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q3b	-- My classmate(s) pay attention to me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q4a	-- My classmate(s) give me ideas when I don't know what to do. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q4b	-- My classmate(s) give me ideas when I don't know what to do. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q5a	-- My classmate(s) give me information so I can learn new things. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q5b	-- My classmate(s) give me information so I can learn new things. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q6a	-- My classmate(s) give me good advice. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q6b	-- My classmate(s) give me good advice. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q7a	-- My classmate(s) tell me I did a good job when I've done something well. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q7b	-- My classmate(s) tell me I did a good job when I've done something well. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q8a	-- My classmate(s) nicely tell me when I make mistakes. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q8b	-- My classmate(s) nicely tell me when I make mistakes. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q9a	-- My classmate(s) notice when I have worked hard. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q9b	-- My classmate(s) notice when I have worked hard. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q10a	-- My classmate(s) ask me to join activities. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q10b	-- My classmate(s) ask me to join activities. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q11a	-- My classmate(s) spend time doing things with me. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q11b	-- My classmate(s) spend time doing things with me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec3_q12a	-- My classmate(s) help me with projects in class. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec3_q12b	-- My classmate(s) help me with projects in class. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q1a	-- My close friend understands my feelings. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q1b	-- My close friend understands my feelings. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q2a	-- My close friend sticks up for me if others are treating me badly. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q2b	-- My close friend sticks up for me if others are treating me badly. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q3a	-- My close friend spends time with me when I'm lonely. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q3b	-- My close friend spends time with me when I'm lonely. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q4a	-- My close friend gives me ideas when I don't know what to do. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q4b	-- My close friend gives me ideas when I don't know what to do. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q5a	-- My close friend gives me good advice. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q5b	-- My close friend gives me good advice. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q6a	-- My close friend explains things that I don't understand. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q6b	-- My close friend explains things that I don't understand. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q7a	-- My close friend tells me he or she likes what I do. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q7b	-- My close friend tells me he or she likes what I do. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q8a	-- My close friend nicely tells me when I make mistakes. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q8b	-- My close friend nicely tells me when I make mistakes. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q9a	-- My close friend nicely tells me the truth about how I do on things. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q9b	-- My close friend nicely tells me the truth about how I do on things. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q10a	-- My close friend helps me when I need it. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q10b	-- My close friend helps me when I need it. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q11a	-- My close friend shares his or her things with me. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q11b	-- My close friend shares his or her things with me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec4_q12a	-- My close friend takes time to help me solve my problems. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec4_q12b	-- My close friend takes time to help me solve my problems. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q1a	-- People in my school care about me. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q1b	-- People in my school care about me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q2a	-- People in my school understand me. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q2b	-- People in my school understand me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q3a	-- People in my school listen to me when I need to talk. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q3b	-- People in my school listen to me when I need to talk. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q4a	-- People in my school give me good advice. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q4b	-- People in my school give me good advice. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q5a	-- People in my school help me solve my problems by giving me information. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q5b	-- People in my school help me solve my problems by giving me information. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q6a	-- People in my school explain things that I don't understand. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q6b	-- People in my school explain things that I don't understand. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q7a	-- People in my school tell me how well I do on tasks. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q7b	-- People in my school tell me how well I do on tasks. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q8a	-- People in my school tell me I did a good job when I've done something well. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q8b	-- People in my school tell me I did a good job when I've done something well. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q9a	-- People in my school nicely tell me when I make mistakes. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q9b	-- People in my school nicely tell me when I make mistakes. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q10a	-- People in my school take time to help me decide things. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q10b	-- People in my school take time to help me decide things. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q11a	-- People in my school spend time with me when I need help. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q11b	-- People in my school spend time with me when I need help. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,casch.casch_sec5_q12a	-- People in my school make sure I have the things I need for school. - How often		1, Never | 2, Almost Never | 3, Some of the time | 4, Most of the time | 5, Almost Always | 6, Always | 99, Not Applicable
       ,casch.casch_sec5_q12b	-- People in my school make sure I have the things I need for school. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
    ---   
	--- Additional data:  casss college
	---	
       ,cascol.cascol_sec1_q1a -- My family shows they are proud of me. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q1b	-- My family shows they are proud of me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q2a	-- My family understands me. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q2b	-- My family understands me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q3a	-- My family listens to me when I need to talk. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q3b	-- My family listens to me when I need to talk. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q4a	-- My family makes suggestions when I don't know what to do. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q4b	-- My family makes suggestions when I don't know what to do. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q5a	-- My family gives me good advice. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q5b	-- My family gives me good advice. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q6a	-- My family helps me solve problems by giving me information. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q6b	-- My family helps me solve problems by giving me information. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q7a	-- My family tells me I did a good job when I do something well. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q7b	-- My family tells me I did a good job when I do something well. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q8a	-- My family nicely tells me when I make mistakes. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q8b	-- My family nicely tells me when I make mistakes. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q9a	-- My family rewards me when I've done something well. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q9b	-- My family rewards me when I've done something well. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q10a -- My family helps me practice my activities. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q10b --	My family helps me practice my activities. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q11a -- My family takes time to help me decide things. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q11b -- My family takes time to help me decide things. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q12a -- My family gets me many of the things I need. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec1_q12b -- My family gets me many of the things I need. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec1_q13	-- 13. How often do you see your family? 1, Daily | 2, Weekly | 3, Monthly | 4, Yearly | 5, Never | 99, Not Applicable
       ,cascol.cascol_sec2_q1a	-- My best friend / significant other understands my feelings. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q1b	-- My best friend / significant other understands my feelings. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q2a	-- My best friend / significant other sticks up for me if others are treating me badly. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q2b	-- My best friend / significant other sticks up for me if others are treating me badly. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q3a	-- My best friend / significant other spends time with me when I'm lonely. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q3b	-- My best friend / significant other spends time with me when I'm lonely. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q4a	-- My best friend / significant other gives me ideas when I don't know what to do. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q4b	-- My best friend / significant other gives me ideas when I don't know what to do. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q5a	-- My best friend / significant other gives me good advice. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q5b	-- My best friend / significant other gives me good advice. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q6a	-- My best friend / significant other explains things that I don't understand. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q6b	-- My best friend / significant other explains things that I don't understand. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q7a	-- My best friend / significant other tells me he or she likes what I do. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q7b	-- My best friend / significant other tells me he or she likes what I do. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q8a	-- My best friend / significant other nicely tells me when I make mistakes. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q8b	-- My best friend / significant other nicely tells me when I make mistakes. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q9a	-- My best friend / significant other nicely tells me the truth about how I do on things. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q9b	-- My best friend / significant other nicely tells me the truth about how I do on things. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q10a -- My best friend / significant other helps me when I need it. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q10b -- My best friend / significant other helps me when I need it. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q11a -- My best friend / significant other shares his or her things with me. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q11b --	My best friend / significant other shares his or her things with me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q12a -- My best friend / significant other takes time to help me solve my problems. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec2_q12b -- My best friend / significant other takes time to help me solve my problems. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec2_q13	 -- Who were you thinking of when you rated "My Best Friend/Significant Other?"		1, Best Friend | 2, Significant Other | 3, Other | 99, Not Applicable
       ,cascol.cascol_sec2_q14	 -- How often do you see this person?		1, Daily | 2, Weekly | 3, Monthly | 4, Yearly | 5, Never | 99, Not Applicable
       ,cascol.cascol_sec3_q1a	 -- My friends treat me nicely. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q1b	 -- My friends treat me nicely. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q2a	 -- My friends like most of my ideas and opinions. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q2b	 -- My friends like most of my ideas and opinions. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q3a	 -- My friends pay attention to me. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q3b	 -- My friends pay attention to me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q4a	 -- My friends give me ideas when I don't know what to do. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q4b	 -- My friends give me ideas when I don't know what to do. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q5a	 -- My friends give me information so I can learn new things. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q5b	 -- My friends give me information so I can learn new things. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q6a	 -- My friends give me good advice. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q6b	 -- My friends give me good advice. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q7a	 -- My friends tell me I did a good job when I've done something well. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q7b	 --	My friends tell me I did a good job when I've done something well. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q8a	 --	My friends nicely tell me when I make mistakes. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q8b	 -- My friends nicely tell me when I make mistakes. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q9a	 --	My friends notice when I have worked hard. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q9b	 -- My friends notice when I have worked hard. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q10a --	My friends ask me to join activities. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q10b --	My friends ask me to join activities. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q11a --	My friends spend time doing things with me. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q11b --	My friends spend time doing things with me. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q12a -- My friends help me with projects in class. - How often		1, Never | 2, Almost Never | 3, Some of the TIme | 4, Most of the TIme | 5, Almost Always | 6, Always | 99, Not Applicable
       ,cascol.cascol_sec3_q12b --	My friends help me with projects in class. - Important		1, Not Important | 2, Important | 3, Very Important | 99, Not Applicable
       ,cascol.cascol_sec3_q13	 -- How often do you see these friends?		1, Daily | 2, Weekly | 3, Monthly | 4, Yearly | 5, Never | 99, Not Applicable
---	
from rcap_ctau_sample_info_joined_view si
where si_tube_id ilike '%_1_1'
and (tc_administrator is not null OR tc_interview_date is not null);
