---- A helper view that unites CAPSCA5 from CBT and CTRN-MAIN
create or replace view view_capsca_main_and_cbt
as
select
    project_id,
    source_subject_id,
    event_name,
    caps_summary_a1,
    caps_summary_b1_sev_q1,
    caps_summary_b2_sev_q2,
    caps_summary_b3_sev_q3,
    caps_summary_b4_sev_q4,
    caps_summary_b5_sev_q5,
    caps_summary_c1_sev_q6,
    caps_summary_c2_sev_q7,
    caps_summary_d1_sev_q8,
    caps_summary_d2_sev_q9,
    caps_summary_d3_sev_q10,
    caps_summary_d4_sev_q11,
    caps_summary_d5_sev_q12,
    caps_summary_d6_sev_q13,
    caps_summary_d7_sev_q14,
    caps_summary_e1_sev_q15,
    caps_summary_e2_sev_q16,
    caps_summary_e3_sev_q17,
    caps_summary_e4_sev_q18,
    caps_summary_e5_sev_q19,
    caps_summary_e6_sev_q20,
    caps_summary_f1_q22,
    caps_summary_g1_sev_q23,
    caps_summary_g2_sev_q24,
    caps_summary_g3_sev_q25,
    caps_summary_validity_q26,
    caps_summary_severity_q27,
    caps_summary_improve_q28,
    caps_sum_depers_sev_q29,
    caps_sum_dereal_sev_q30,
    caps_sum_ptsd_present,
    caps_summary_dissoc as caps_sum_dissociative,
    caps_sum_delayed,
    caps_date
from rcap_capsca5

union all

select
    project_id,
    source_subject_id,
    event_name,
    caps_summary_a1,
    caps_summary_b1_sev_q1,
    caps_summary_b2_sev_q2,
    caps_summary_b3_sev_q3,
    caps_summary_b4_sev_q4,
    caps_summary_b5_sev_q5,
    caps_summary_c1_sev_q6,
    caps_summary_c2_sev_q7,
    caps_summary_d1_sev_q8,
    caps_summary_d2_sev_q9,
    caps_summary_d3_sev_q10,
    caps_summary_d4_sev_q11,
    caps_summary_d5_sev_q12,
    caps_summary_d6_sev_q13,
    caps_summary_d7_sev_q14,
    caps_summary_e1_sev_q15,
    caps_summary_e2_sev_q16,
    caps_summary_e3_sev_q17,
    caps_summary_e4_sev_q18,
    caps_summary_e5_sev_q19,
    caps_summary_e6_sev_q20,
    caps_summary_f1_q22,
    caps_summary_g1_sev_q23,
    caps_summary_g2_sev_q24,
    caps_summary_g3_sev_q25,
    caps_summary_validity_q26,
    caps_summary_severity_q27,
    caps_summary_improve_q28,
    caps_sum_depers_sev_q29,
    caps_sum_dereal_sev_q30,
    caps_sum_ptsd_present,
    caps_sum_dissociative as caps_sum_dissociative,
    caps_sum_delayed,
    caps_date
from rcap_cbt_capsca5
;